version: '3'
services:

  work_a:
    build: 
      context: ../
      dockerfile: deployment/dockerfile
    ports:
      - 41234
    networks:
      - blockchain_network1

  work_b:
    build: 
      context: ../
      dockerfile: deployment/dockerfile
    ports:
      - 41234
    networks:
      - blockchain_network2

  work_c:
    build: 
      context: ../
      dockerfile: deployment/dockerfile
    ports:
      - 41234
    networks:
      - blockchain_network3

networks:
  blockchain_network1:
    driver: bridge
  blockchain_network2:
    driver: bridge
  blockchain_network3:
    driver: bridge